[workspace]
members = [
    "chatty",
    "chatty-arg",
    "chatty-service",
    "chatty-primitives",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = "1.0"