[workspace]
members = [
    "chatty",
    "chatty-rag",
    "chatty-service",
    "chatty-prompt",
    "chatty-config",
    "chatty-gemini",
    "chatty-data-handler",
    "chatty-text",
    "chatty-cli",
    "chatty-toolset",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
serde_json = "1.0"
actix-web = "4"
colored = "2.0"
lazy_static = "1.5.0"
toml = "0.8.19"
# rig-core = "0.6.0"
rig-core = { path = "../../../codebuffer/rig/rig-core" } # v0.6.0
clap = { version = "4.5.23", features = ["derive"] }
thiserror = "2.0.9"
anyhow = "1.0.95"
chrono = { version = "0.4.39", features = ["serde"] } 
reqwest = { version = "0.12", features = ["blocking", "json"] }
