[package]
name = "chatty"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
clap.workspace = true
chatty-service = { path = "../chatty-service" }
chatty-cli = { path = "../chatty-cli" }