[package]
name = "chatty-service"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
actix-web.workspace = true
colored.workspace = true
serde.workspace = true
chatty-config = { path = "../chatty-config" }